# Generated by Django 5.0.4 on 2024-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ("last_name",),
                "verbose_name": "студент",
                "verbose_name_plural": "студенты",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="учится"),
        ),
    ]
